### PR TITLE
Count other teacher roles in user dashboard and teacher visit reports

### PR DESCRIPTION
**Pull request by gmanaud**
Hi,

A proposal to consider other teacher roles (non-editor teacher or custom role) in the count of teachers in user dashboard as well as for the last teacher visits in the reports.

I also added accents on capital E in french strings.

Don't hesitate to tell me if it's not suitable.

### CODE REVIEW

**Comment by gmanaud** [comment]
I forgot to create separate branches in git to make multiple pull requests, sorry.

I also added settings to customize the subject line and conclusion of the report by email.

Do you want me to do a separate pull request?

**Comment by oliviervalentin** [comment]
No, that's all right for me, I'm not so familiar with GitHub, so it's more simple ! :)
I check that as soon as possible, but that's a good idea !

**Comment by oliviervalentin** [comment]
Ok tested, allright for me, we can merge !
I also made a test on my testing instance : it didn't took more time for my task (4 minutes for teachers).

On the other side, we should think of a mean for teachers dashboard to indicates roles included in reports calculation and columns. For now, for example, it's only mentionned "Teachers", whereas we could count other roles in the number of teachers enrolled in each course !
Do you think we still can merge right now ? Or should I first work on teacher dashboard ?

That's a more important project to do : I must work on the teacher dashboard presentation, show or hide columns according to settings, indicate in columns which roles are included, add possibility in settings to activate or desactive tools (reinitialize, uneroll cohorts...).

I add an issue about all this.

Thanks again for your work !
Olivier

**Comment by gmanaud** [comment]
For me, a teacher, whether he is a editor or not, is a teacher, so I don't have a problem with it being mixed. In that case, it doesn't seem problematic to me to merge now.

But you're right, the different roles should be displayed on the teacher dashboard.

**Comment by oliviervalentin** [comment]
OK let's merge !
I'll start redesign of teachers dashboard as soon as possible. I've added issue #66 for this, feel free to complete it with other ideas.
Olivier

**Pull request merged**
